export const RSS_FEEDS = [
  'https://feeds.feedburner.com/TheHackersNews',
  'https://www.bleepingcomputer.com/feed/',
  'https://www.securityweek.com/feed',
  'https://isc.sans.edu/rssfeed.xml',
  'https://www.zerodayinitiative.com/rss/published/',
  'https://www.exploit-db.com/rss.xml',
  'https://www.microsoft.com/en-us/security/blog/feed/',
  'https://unit42.paloaltonetworks.com/feed/',
  'https://research.checkpoint.com/feed/',
  'https://www.crowdstrike.com/blog/feed/',
  'https://portswigger.net/research/rss',
  'https://googleprojectzero.blogspot.com/feeds/posts/default',
  'https://github.blog/security/feed/',
  'https://snyk.io/blog/feed/',
];

export const HIGH_RISK_KEYWORDS = [
  'zero-day',
  'zero day',
  'rce',
  'remote code execution',
  'privilege escalation',
  'authentication bypass',
  'actively exploited',
  'in the wild',
  'critical vulnerability',
  'cvss 9',
  'cvss 10',
  'cvss9',
  'cvss10',
  'critical severity',
  'wormable',
  'pre-auth',
  'preauthentication',
];

export const HIGH_SEVERITY_KEYWORDS = [
  'exploit',
  'exploited',
  'ransomware',
  'malware',
  'apt',
  'supply chain',
  'remote execution',
  'arbitrary code',
  'sandbox escape',
  'use-after-free',
  'heap overflow',
  'buffer overflow',
  'sql injection',
  'ssrf',
  'xxe',
  'deserialization',
  'kev',
  'emergency patch',
  'out-of-band',
  'poc',
  'proof of concept',
];

export const MEDIUM_SEVERITY_KEYWORDS = [
  'vulnerability',
  'cve-',
  'patch tuesday',
  'security update',
  'security advisory',
  'denial of service',
  'dos',
  'ddos',
  'phishing',
  'credential stuffing',
  'brute force',
  'information disclosure',
  'cross-site scripting',
  'xss',
  'csrf',
  'medium severity',
  'high severity',
];

export const VENDOR_TAGS = [
  'Microsoft',
  'Google',
  'Apple',
  'Cisco',
  'VMware',
  'Oracle',
  'Adobe',
  'Linux',
  'Apache',
  'nginx',
  'OpenSSL',
  'Citrix',
  'Fortinet',
  'Palo Alto',
  'CrowdStrike',
  'Checkpoint',
  'Snyk',
  'GitHub',
  'Amazon',
  'AWS',
  'Azure',
  'Kubernetes',
  'Docker',
  'Chrome',
  'Firefox',
  'Intel',
  'AMD',
  'NVIDIA',
  'Samsung',
  'Qualcomm',
];

export const ATTACK_TYPE_KEYWORDS = {
  ransomware: 'Ransomware',
  phishing: 'Phishing',
  'supply chain': 'Supply chain',
  malware: 'Malware',
  spyware: 'Spyware',
  trojan: 'Trojan',
  botnet: 'Botnet',
  ddos: 'DDoS',
  'denial of service': 'DoS',
  'sql injection': 'SQLi',
  'cross-site scripting': 'XSS',
  xss: 'XSS',
  'privilege escalation': 'Privilege escalation',
  'remote code execution': 'RCE',
  rce: 'RCE',
  'zero-day': 'Zero-day',
  'zero day': 'Zero-day',
  backdoor: 'Backdoor',
  rootkit: 'Rootkit',
  cryptojacking: 'Cryptojacking',
};

export const CVSS_REGEX = /cvss\s*[:\s]*([0-9]+(?:\.[0-9]+)?)/gi;

export const CVE_REGEX = /CVE-\d{4}-\d{4,7}/gi;
